---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: mastodon-redis
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.5
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
