---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: mastodon-redis
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.12
    redisSecret:
      name: mastodon-generated-redis
      key: password
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.storage.persistence }}
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
