---
apiVersion: v1
kind: Secret
metadata:
  name: mastodon-generated-secrets
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: SECRET_KEY_BASE,OTP_SECRET
data:
  {{- if .Values.mastodon.mastodon.s3.enabled }}
  AWS_ACCESS_KEY_ID: "{{ .Values.mastodon.mastodon.s3.access_key | b64enc }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.mastodon.mastodon.s3.access_secret | b64enc }}"
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: mastodon-generated-redis
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
---
apiVersion: v1
kind: Secret
metadata:
  name: mastodon-generated-smtp
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  login: mastodon
