---
apiVersion: v1
kind: Secret
metadata:
  name: mastodon-secrets
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: SECRET_KEY_BASE,OTP_SECRET
data: {}

---
apiVersion: v1
kind: Secret
metadata:
  name: mastodon-redis
data:
  redis-password: ""

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mastodon-smtp
#   annotations:
#     secret-generator.v1.mittwald.de/autogenerate: password
# data:
#   login: mastodon
