apiVersion: v2
name: enoki-mastodon
description: Mastodon deployment specific to Enoki

type: application

version: 0.3.5

appVersion: 4.2.1

dependencies:
  - name: mastodon
    version: "4.0.8"
    repository: file://../mastodon
  - name: kubernetes-secret-generator
    version: "3.4.0"
    repository: "https://helm.mittwald.de"
    condition: global.install_operator
  - name: postgresql
    version: "0.2.0"
  - name: redis
    version: "0.2.0"
