mastodon:
  mastodon:
    secrets:
      existingSecret: "mastodon-generated-secrets"
    smtp:
      existingSecret: "mastodon-generated-smtp"

  postgresql:
    # we are managing our own database instance
    enabled: false
    postgresqlHostname: mastodon-postgres-primary
    auth:
      database: mastodon-postgres
      username: mastodon-postgres
      existingSecret: mastodon-postgres-pguser-mastodon-postgres

  redis:
    # we are managing our own redis instance
    enabled: false
    hostname: mastodon-redis
    auth:
      existingSecret: mastodon-generated-redis

  elasticsearch:
    enabled: false

global:
  install_operator: false
