mastodon:
  mastodon:
    secrets:
      existingSecret: "mastodon-secrets"
    smtp:
      existingSecret: "mastodon-smtp"

  postgresql:
    # we are managing our own database instance
    enabled: false
    postgresqlHostname: localhost
    auth:
      password: "foobar"
      # todo
      # existingSecret: ""

  redis:
    # we are managing our own redis instance
    enabled: false
    hostname: localhost
    auth:
      existingSecret: "mastodon-redis"

  elasticsearch:
    enabled: false
